// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdkrmxpisgjdgwhykpns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNka3JteHBpc2dqZGd3aHlrcG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODU0MjIsImV4cCI6MjA3MjQ2MTQyMn0.yKskwjvN6jNfok7tOvM4aw8b04HuB55YM2uCtK5tYXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});