// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbxmgtnuynbdnzjrzkgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieG1ndG51eW5iZG56anJ6a2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDAwNDksImV4cCI6MjA3MTE3NjA0OX0.8Rd5ZBF5PrbRc1yqV3kQPX8PJmsaW0H6OvlZBkCjJsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});